#!/usr/bin/env python3
"""
Environment management script for forkstack with Turso + Tigris + Doppler.

Usage:
    python envs.py create <env-name>   - Create new environment
    python envs.py switch <env-name>   - Switch to environment
    python envs.py delete <env-name>   - Delete environment
    python envs.py list                - List all environments
"""
import os
import sys
import subprocess
import json
from pathlib import Path

# Import utilities
from env_utils import (
    PROJECT_NAME,
    get_current_env,
    create_database_branch,
    delete_database_branch,
    get_database_token,
    create_bucket_fork,
    delete_bucket_fork,
    get_bucket_name,
)

PROTECTED_ENVS = ["dev", "prod"]  # Can't be deleted


def run_cmd(cmd, capture=True, env=None):
    """Run shell command."""
    if env is None:
        env = os.environ
    if capture:
        result = subprocess.run(cmd, shell=True, capture_output=True, text=True, env=env)
        return result.returncode == 0, result.stdout.strip()
    else:
        return subprocess.run(cmd, shell=True, env=env).returncode == 0, None


def cmd_create(env_name):
    """Create a new environment (database branch, bucket fork, Doppler env)."""
    print(f"Creating environment: {env_name}")

    # 1. Create database branch
    print(f"  Creating database branch: {PROJECT_NAME}-{env_name}")
    success, _ = run_cmd(
        f"turso db create {PROJECT_NAME}-{env_name}",
        capture=False,
    )
    if not success:
        print(f"  ✗ Failed to create database branch")
        return False

    # 2. Get database credentials
    print(f"  Getting database URL...")
    success, url = run_cmd(f"turso db show {PROJECT_NAME}-{env_name} --url")
    if not success:
        print(f"  ✗ Failed to get database URL")
        return False

    print(f"  Getting database token...")
    success, token = run_cmd(f"turso db tokens create {PROJECT_NAME}-{env_name}")
    if not success:
        print(f"  ✗ Failed to get database token")
        return False

    # 3. Create storage bucket fork
    bucket_name = get_bucket_name()
    print(f"  Creating storage bucket: {bucket_name}")
    success, _ = run_cmd(
        f"aws s3 mb s3://{bucket_name} --endpoint-url https://s3.amazonaws.com",
        capture=False,
    )
    if not success:
        print(f"  ✗ Failed to create storage bucket")
        return False

    # 4. Create Doppler environment
    print(f"  Creating Doppler environment: {env_name}")
    success, _ = run_cmd(
        f"doppler environments create {env_name}",
        capture=False,
        env={**os.environ, "DOPPLER_PROJECT": os.getenv("DOPPLER_PROJECT", "")},
    )
    if not success:
        print(f"  ⚠ Warning: Failed to create Doppler environment")
        print(f"    (Create manually: doppler environments create {env_name})")

    # 5. Copy secrets from production to new environment
    print(f"  Copying secrets from prod...")
    success, _ = run_cmd(
        f"doppler secrets download --environment prod > /tmp/{PROJECT_NAME}-secrets.json",
    )
    if success:
        run_cmd(
            f"doppler secrets upload /tmp/{PROJECT_NAME}-secrets.json --environment {env_name}",
            capture=False,
            env={**os.environ, "DOPPLER_PROJECT": os.getenv("DOPPLER_PROJECT", "")},
        )

    # 6. Write .env.local with credentials
    env_file = Path(".env.local")
    env_content = f"""# Environment: {env_name}
# Generated by envs.py on {__import__("datetime").datetime.now().isoformat()}

# Database (Turso)
DATABASE_URL={url}
DATABASE_AUTH_TOKEN={token}

# Storage (Tigris)
BUCKET_NAME={bucket_name}
AWS_ACCESS_KEY_ID={os.getenv("AWS_ACCESS_KEY_ID", "your_access_key")}
AWS_SECRET_ACCESS_KEY={os.getenv("AWS_SECRET_ACCESS_KEY", "your_secret_key")}

# Secrets (Doppler)
DOPPLER_ENVIRONMENT={env_name}
DOPPLER_PROJECT={os.getenv("DOPPLER_PROJECT", "")}
DOPPLER_TOKEN={os.getenv("DOPPLER_TOKEN", "")}
"""
    env_file.write_text(env_content)
    print(f"  ✓ Created .env.local")

    # 7. Write .current-env
    current_env_file = Path(".current-env")
    current_env_file.write_text(env_name)
    print(f"  ✓ Set current environment to {env_name}")

    print(f"\n✓ Environment '{env_name}' created successfully!")
    print(f"\nNext steps:")
    print(f"  1. Restart your app: make down && make up")
    print(f"  2. Your app now uses isolated {env_name} resources:")
    print(f"     - Database: {url}")
    print(f"     - Storage: {bucket_name}")
    print(f"     - Secrets: Doppler {env_name} environment")
    return True


def cmd_switch(env_name):
    """Switch to an existing environment."""
    print(f"Switching to environment: {env_name}")

    # Get database credentials
    print(f"  Getting database URL...")
    success, url = run_cmd(f"turso db show {PROJECT_NAME}-{env_name} --url")
    if not success:
        print(f"  ✗ Environment '{env_name}' does not exist")
        return False

    print(f"  Getting database token...")
    success, token = run_cmd(f"turso db tokens create {PROJECT_NAME}-{env_name}")
    if not success:
        print(f"  ✗ Failed to get database token")
        return False

    # Get bucket name
    bucket_name = f"{PROJECT_NAME}-bucket-{env_name}"

    # Update .env.local
    env_file = Path(".env.local")
    env_content = f"""# Environment: {env_name}
# Generated by envs.py on {__import__("datetime").datetime.now().isoformat()}

# Database (Turso)
DATABASE_URL={url}
DATABASE_AUTH_TOKEN={token}

# Storage (Tigris)
BUCKET_NAME={bucket_name}
AWS_ACCESS_KEY_ID={os.getenv("AWS_ACCESS_KEY_ID", "your_access_key")}
AWS_SECRET_ACCESS_KEY={os.getenv("AWS_SECRET_ACCESS_KEY", "your_secret_key")}

# Secrets (Doppler)
DOPPLER_ENVIRONMENT={env_name}
DOPPLER_PROJECT={os.getenv("DOPPLER_PROJECT", "")}
DOPPLER_TOKEN={os.getenv("DOPPLER_TOKEN", "")}
"""
    env_file.write_text(env_content)

    # Update .current-env
    current_env_file = Path(".current-env")
    current_env_file.write_text(env_name)

    print(f"\n✓ Switched to environment '{env_name}'")
    print(f"\nNext steps:")
    print(f"  1. Restart your app: make down && make up")
    return True


def cmd_delete(env_name):
    """Delete an environment."""
    if env_name in PROTECTED_ENVS:
        print(f"✗ Cannot delete protected environment: {env_name}")
        return False

    print(f"Deleting environment: {env_name}")

    # Delete database branch
    print(f"  Deleting database branch: {PROJECT_NAME}-{env_name}")
    success, _ = run_cmd(
        f"turso db destroy {PROJECT_NAME}-{env_name} -y",
        capture=False,
    )
    if not success:
        print(f"  ⚠ Warning: Failed to delete database branch")

    # Delete storage bucket
    bucket_name = f"{PROJECT_NAME}-bucket-{env_name}"
    print(f"  Deleting storage bucket: {bucket_name}")
    success, _ = run_cmd(
        f"aws s3 rb s3://{bucket_name} --force --endpoint-url https://s3.amazonaws.com",
        capture=False,
    )
    if not success:
        print(f"  ⚠ Warning: Failed to delete storage bucket")

    # Delete Doppler environment (optional - keep secrets for backup)
    print(f"  Note: Doppler environment not deleted (kept for backup)")

    # Clean up .current-env if this was the active environment
    current_env_file = Path(".current-env")
    if current_env_file.exists() and current_env_file.read_text().strip() == env_name:
        current_env_file.unlink()
        print(f"  ✓ Cleared current environment")

    print(f"\n✓ Environment '{env_name}' deleted")
    return True


def cmd_list():
    """List all environments."""
    print("Listing Turso database branches:")
    success, output = run_cmd("turso db list", capture=False)
    if not success:
        print("✗ Failed to list databases")
        return False

    print("\nListing Tigris buckets:")
    success, output = run_cmd(
        f"aws s3 ls --endpoint-url https://s3.amazonaws.com | grep {PROJECT_NAME}",
        capture=False,
    )
    if not success:
        print("✗ Failed to list buckets")
        return False

    return True


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)

    command = sys.argv[1]

    if command == "create":
        if len(sys.argv) < 3:
            print("Usage: python envs.py create <env-name>")
            sys.exit(1)
        sys.exit(0 if cmd_create(sys.argv[2]) else 1)

    elif command == "switch":
        if len(sys.argv) < 3:
            print("Usage: python envs.py switch <env-name>")
            sys.exit(1)
        sys.exit(0 if cmd_switch(sys.argv[2]) else 1)

    elif command == "delete":
        if len(sys.argv) < 3:
            print("Usage: python envs.py delete <env-name>")
            sys.exit(1)
        sys.exit(0 if cmd_delete(sys.argv[2]) else 1)

    elif command == "list":
        sys.exit(0 if cmd_list() else 1)

    else:
        print(f"Unknown command: {command}")
        print(__doc__)
        sys.exit(1)


if __name__ == "__main__":
    main()
